/*
 * APIMATICCalculator.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */
using System;
using APIMATICCalculator.PCL.Controllers;

namespace APIMATICCalculator.PCL
{
    public partial class APIMATICCalculatorClient
    {

        /// <summary>
        /// Singleton access to SimpleCalculator controller
        /// </summary>
        public SimpleCalculatorController SimpleCalculator
        {
            get
            {
                return SimpleCalculatorController.Instance;
            }
        }

        /// <summary>
        /// Client constructor
        /// </summary>
        public APIMATICCalculatorClient()
        {
        }
    }
}