/*
 * APIMATICCalculator.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */
using System;

namespace APIMATICCalculator.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://examples.apimatic.io/apps/calculator";

    }
}